version: "3"

services: 
  buildapp:
    build:
      dockerfile: build.dockerfile
    volumes:
      - cd1:/tmp
  
  app:
    build:
      dockerfile: app.dockerfile
    volumes:
      - cd1:/tmp
    ports:
      - 8081:8080
    depends_on:
      - buildapp
    
volumes:
  cd1:
  

