version: "2.29.6"

services: 
  buildapp:
    build:
      dockerfile: build.dockerfile
    volumes:
      - cd:/tmp
  
  app:
    build:
      dockerfile: app.dockerfile
    volumes:
      - cd:/tmp
    ports:
      - 8081:8080
    depends_on:
      - buildapp
    
volumes:
  cd:
  

